replicas: 1

backend:
  name: backend-svc
  image: shreybatra/sample-backend
  service:
    type: ClusterIP
    port: 8000
  env:
    REDIS_URI: redis://redis-svc:6379

frontend:
  name: frontend-svc
  image: shreybatra/sample-frontend
  service:
    type: NodePort
    port: 5173
    nodePort: 31000
  env:
    BACKEND_URL: http://backend-svc:8000

redis:
  name: redis-svc
  image: redis
  service:
    type: ClusterIP
    port: 6379
